# NUMPY

In [2]:
import numpy as np

In [ ]:
ar=np.array(list(range(10)))

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
ar**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

ARRAY OPERATION

In [ ]:
b=ar+5

In [ ]:
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
c=ar-10

In [ ]:
c

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [ ]:
c.shape

(10,)

In [ ]:
c=c.reshape((-1,1))

In [ ]:
c.shape

(10, 1)

In [ ]:
print(ar)
print(b)
ar+b

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
ar**b

array([             0,              1,            128,           6561,
               262144,        9765625,      362797056,    13841287201,
         549755813888, 22876792454961])

In [ ]:
print(ar)
print(c)
ar+c

[0 1 2 3 4 5 6 7 8 9]
[[-10]
 [ -9]
 [ -8]
 [ -7]
 [ -6]
 [ -5]
 [ -4]
 [ -3]
 [ -2]
 [ -1]]


array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1],
       [ -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2],
       [ -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5],
       [ -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6],
       [ -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7],
       [ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8]])

In [ ]:
d=np.array([[1,2,3],[4,5,6]])

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

function in NUMPY

In [ ]:
a=np.zeros((3,4))

In [ ]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones((4,3), dtype='int')

In [ ]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a=np.ones((4,3),dtype='int')
a*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Random Fuctions

In [ ]:
a=np.random.randint(1,10,(5,1))

In [ ]:
np.random.randint(1,10)

3

In [ ]:
a=np.random.randint(1,10,(3,4))

In [ ]:
print(a)

[[1 8 8 6]
 [2 4 7 7]
 [2 6 1 1]]


In [ ]:
a.shape

(3, 4)

In [ ]:
a[ : ,:]

array([[1, 8, 8, 6],
       [2, 4, 7, 7],
       [2, 6, 1, 1]])

In [ ]:
a[1:,1:3]

array([[4, 7, 7],
       [6, 1, 1]])

##More Function
min,max,mean,variance,std

In [ ]:
a=np.array([[1,3],[2,4]])

In [ ]:
a

array([[1, 3],
       [2, 4]])

In [ ]:
a.min()

1

In [ ]:
a.max()

4

In [ ]:
np.min(a)

1

In [ ]:
np.std(a)

1.118033988749895

In [ ]:
np.std(a,axis=0)

array([0.5, 0.5])

In [ ]:
np.var(a, axis=1)

array([1., 1.])

In [4]:
a=np.array([1,2,3])
b=np.array([3,4,5])

In [ ]:
np.stack((a,b))

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
np.stack((b,a),axis =1)

array([[3, 1],
       [4, 2],
       [5, 3]])